apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: murmur-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: murrr.site
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: murmur-backend-svc
                port:
                  number: 80
          - path: /login/oauth2/code/
            pathType: Prefix
            backend:
              service:
                name: murmur-backend-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: murmur-frontend-svc
                port:
                  number: 80
    - http:
        paths:
          - path: /api/swagger
            pathType: Prefix
            backend:
              service:
                name: murmur-backend-svc
                port:
                  number: 80
